[project]
name = "cluetooth-sync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yibo Wei", email = "david_wyb2001@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "adbc-driver-postgresql>=1.11.0",
    "google-cloud-storage>=3.10.1",
    "polars>=1.39.3",
    "pynacl>=1.6.2",
    "rich>=15.0.0",
    "typer>=0.24.1",
]

[project.scripts]
cluetooth = "cluetooth_sync:main"
cluetooth-sync = "cluetooth_sync.cli:sync_main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[tool.basedpyright]
typeCheckingMode = "standard"

[dependency-groups]
dev = [
    "basedpyright>=1.39.1",
    "pytest>=9.0.3",
    "ruff>=0.15.11",
    "testcontainers>=4.14.2",
]
